version: "3.3"

services:  
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8086:8086"
        expose:
            - "8086"
        volumes:
            # Data persistency
            # sudo mkdir -p /srv/docker/influxdb/data
            - /srv/docker/influxdb/data:/var/lib/influxdb
    
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "25565:25565"
        # env_file: 
        #     - 'env.grafana'
        user: "0"
        links:
            - influxdb
        volumes:
            # Data persistency
            # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
            - ./config/grafana.ini:/etc/grafana/grafana.ini
            - /srv/docker/grafana/data:/var/lib/grafana


    datahandler:    
        build: 
            context: .
            dockerfile: components/data_handler/docker/Dockerfile
        # image: data_handler:staging
        depends_on:
            - influxdb
        environment:
            ADDRESS: "influx.itu.dk"
            PORT: "9001"
            USER: "smartreader"
            PASSWORD: "4mp3r3h0ur"
            TOPIC: "IoT2020sec/meters"
            DBHOST: "influxdb"
            DBPORT: "8086"
